export const groceryCategories = [
  "Fruits and Vegetables",
  "Dairy Products",
  "Meat and Seafood",
  "Bakery and Bread",
  "Pantry Staples",
  "Snacks and Beverages",
  "Household and Personal Care",
  "Frozen",
  "Grains",
  "Instant Goods",
  "Can",
];

export const groceryMeasurements = [
  "1 Kilogram (kg)",
  "1/2 Kilogram (kg)",
  "1/3 Kilogram (kg)",
  "1/4 Kilogram (kg)",
  "1 Gram (g)",
  "1/2 Gram (g)",
  "1/3 Gram (g)",
  "1/4 Gram (g)",
  "1 Ounce (oz)",
  "1 Liter (L)",
  "1 Piece",
  "Bundle",
  "1 Dozen",
  "1 Sack",
  "1 Box",
  "1 Can",
];
